URLS = {
    "www.cnn.com": {"name": "CNN", "bias":"left"},
    "edition.cnn.com": {"name": "CNN", "bias":"left"},
    "www.nytimes.com": {"name": "New York Times", "bias":"left"},
    "www.theguardian.com": {"name": "The Guardian", "bias":"left"},
    "abcnews.go.com":{"name": "ABC", "bias": "left"},
    "www.washingtonpost.com": {"name": "Washington Post", "bias": "left"},
    "apnews.com": {"name": "Associated Press", "bias":"center"},
    "www.reuters.com": {"name": "Reuters", "bias":"center"},
    "www.ft.com": {"name": "Financial Times", "bias":"center"},
    "www.thehill.com": {"name": "The Hill", "bias": "center"},
    "upi.com": {"name": "UPI", "bias": "center"},
    "fortune.com": {"name": "Fortune", "bias": "center"},
    "www.foxnews.com": {"name": "Fox News", "bias":"right"},
    "www.nypost.com": {"name": "New York Post", "bias":"right"},
    "www.wsj.com": {"name": "Wall Street Journal", "bias":"right"},
    "www.nationalreview.com": {"name": "National Review", "bias":"right"},
    "reason.com": {"name": "Reason", "bias": "right"},
    "bostonherald.com": {"name":"Boston Herald", "bias": "right"}
}